/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.Color;

/**
 *
 * @author haseena
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        customerpanle.setPanelColor(Color.decode("#1B3C3F"));
//        dashboardbtn.setBackground(Color.decode("#4F7074"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerpanle = new frontend.PanelCustom();
        jLabel1 = new javax.swing.JLabel();
        dashboardbtn = new frontend.MyButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        myButton2 = new frontend.MyButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        myButton4 = new frontend.MyButton();
        myButton3 = new frontend.MyButton();
        myButton5 = new frontend.MyButton();
        myButton1 = new frontend.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerpanle.setBackground(new java.awt.Color(27, 60, 63));
        customerpanle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/monitor 1.png"))); // NOI18N
        customerpanle.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 30, 30));

        dashboardbtn.setBackground(new java.awt.Color(79, 112, 116));
        dashboardbtn.setText("Dashboard");
        dashboardbtn.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        customerpanle.add(dashboardbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 90, 180, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/bill 1.png"))); // NOI18N
        customerpanle.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/car 1.png"))); // NOI18N
        customerpanle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 50, 40));

        myButton2.setText("Cars");
        myButton2.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        customerpanle.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 162, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/client 1.png"))); // NOI18N
        customerpanle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/real-estate 1.png"))); // NOI18N
        customerpanle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 40, 30));

        myButton4.setText("Rental");
        myButton4.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        customerpanle.add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 160, 50));

        myButton3.setText("Clinets");
        myButton3.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        customerpanle.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        myButton5.setText("Bills");
        myButton5.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        customerpanle.add(myButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 92, 169, 50));

        myButton1.setText("Clients");
        myButton1.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        customerpanle.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 170, 50));

        jPanel1.add(customerpanle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1210, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.PanelCustom customerpanle;
    private frontend.MyButton dashboardbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private frontend.MyButton myButton1;
    private frontend.MyButton myButton2;
    private frontend.MyButton myButton3;
    private frontend.MyButton myButton4;
    private frontend.MyButton myButton5;
    // End of variables declaration//GEN-END:variables
}
